---
- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
    - name: Installing Nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes