---
- name: Installing Nginx
  hosts: web
  become: true
  tasks:
    - name: Installing Nginx
      ansible.builtin.package:
        name: Nginx
        state: insatlled
    - name: Start Nginx
      service:
        name: Nginx
        state: started