---
- name: Multiplay 1
  hosts: web
  connection: local
  tasks:
    - name: Play 1 Task 1
      debug:
        msg: "Play 1 Task 1"
    
    - name: Play 1 Task 2
      debug:
        msg: "Play 1 Task 2"

- name: Multiplay 2
  hosts: local
  connection: local
  tasks:
    - name: Play 2 Task 1
      debug:
        msg: "Play2 Task 1"

    - name: Play 2 Task 2
      debug:
        msg: "Play 2 Task 2"  

