- name: variables from Play level
  hosts: localhost
  vars_files:
  - variables.yml
  tasks:
  - name: check variables
    vars:
      # Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}}, Trainer is {{Trainer}} and Experience is {{Experience}}"