---
- name: Variables
  hosts: local
  connection: local
  vars_files:
    - variables.yml
  tasks:
    - name: Print Variables
      debug:
        msg: " {{ NAME }} is working in {{ COMPANY }} from past {{ DURATION }} years"