- name: variables from Play level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Siva Kumar"
    Experience: "10 Yrs"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}}, Trainer is {{Trainer}} and Experience is {{Experience}}"