---
- name: prompt variables
  hosts: local
  connection: local
  vars_prompt:
    - name: username
      prompt: What is your name ?
      private: false
    
    - name: password
      prompt: what is password ?
      private: yes
  
  tasks:
    - name: print username & password
      debug:
        - msg: " Entered Username: {{ username }}"
        - msg: " Entered Password: {{ password }}"
