- name: variables from Inventory
  hosts: localhost
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}}, Trainer is {{Trainer}} and Experience is {{Experience}}"