---
- name: datatypes
  hosts: local
  connection: local
  vars:
    User:
      NAME: "Mohan Krishna"
      AGE: 33
    Skills:
      - Apache
      - Linux
      - Jboss
    Experience:
      Apache: 8
      Linux: 5
      Jboss: 7
  tasks:
    - name: pint user details key variables
      debug:
        msg:
          - "Name: {{ User.NAME }}"
          - "Age: {{ User.AGE }}"
    - name: pint skills list
      debug:
        msg: Skills are {{ Skills }}
    - name: print experience mapped to each Skill
      debug:
        msg: Experience in {{ Experience }}