- name: condotions
  hosts: localhost
  become: yes
  tasks:
    - name: check if user exists or not
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true
    
    - name: print user name
      ansible.builtin.debug:
        msg: "User output {{user}}"

    - name: print output
      ansible.builtin.debug:
        msg: "User output {{user.rc}}"

    - name: create user
      ansible.builtin.user:
        name: roboshop
      when: user.rc != 0    