# - name: condotions
#   hosts: localhost
#   become: yes
#   tasks:
#     - name: check if user exists or not
#       ansible.builtin.command: id roboshop
#       register: user
#       ignore_errors: true
    
#     - name: print user name
#       ansible.builtin.debug:
#         msg: "User output {{user}}"

#     - name: print output
#       ansible.builtin.debug:
#         msg: "User output {{user.rc}}"

#     - name: create user
#       ansible.builtin.user:
#         name: roboshop
#       when: user.rc != 0    

---
- name: condition
  hosts: local
  connection: local
  vars_prompt:
    - name: num
      prompt: Enter a number
      private: false
  
  tasks:
    - name: greater
      debug:
        msg: "Entered number is greater than 100"
      when: num > 100
  
  tasks:
    - name: lesser
      debug:
        msg: "Entered number is less than 100"
      when: num < 100