- name: condotions
  hosts: localhost
  tasks:
    - name: check if user exists or not
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true
    
    - name: print user name
      ansible.builtin.debug:
        msg: "User output {{user}}"