- name: loops
  hosts: localhost
  tasks:
    - name: print pesrsons
      ansible.builtin.package:
        msg: "{{item}}"
        state: present
      loop:
      - git
      - mysql
      - postfix


