---
- name: conditions
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: install mysql
      package:
        name: mysql
        state: present
      when: ansible_os_family == "debian"