; 172.179.1.1
; 172.179.1.2

; [localhost]
; localhost


[local:vars]
NAME= Mohan Krishna
COMPANY= Accenture
DURATION= 5

[web]
172.31.23.137

[local]
localhost

[node]
172.31.16.159 NAME= Mohan Krishna COMPANY= Accenture DURATION= 5
172.31.18.55 NAME= Mohan Krishna COMPANY= HCL DURATION= 4

; [catalouge]
; 192.168.0.3
; 192.168.0.4

; [cart]
; 192.168.0.5
; 192.168.0.6

; [roboshop:children]
; web
; catalouge
; cart